# .github/workflows/deploy-sites.yml
name: Auto-Deploy All Projects

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy Product Landing Page
      if: hashFiles('CoursesCertificationProjects/Responsive-Web-Design/Product-Landing-Page/index.html') != ''
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./CoursesCertificationProjects/Responsive-Web-Design/Product-Landing-Page
        destination_dir: product-landing-page
        
    - name: Deploy Survey Form
      if: hashFiles('CoursesCertificationProjects/Responsive-Web-Design/Survey-Form/index.html') != ''
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./CoursesCertificationProjects/Responsive-Web-Design/Survey-Form
        destination_dir: survey-form

    - name: Deploy Technical Documentation
      if: hashFiles('CoursesCertificationProjects/Responsive-Web-Design/Technical-Documentation/index.html') != ''
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./CoursesCertificationProjects/Responsive-Web-Design/Technical-Documentation
        destination_dir: technical-documentation

    - name: Deploy Tribute Page
      if: hashFiles('CoursesCertificationProjects/Responsive-Web-Design/Tribute-Page/index.html') != ''
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./CoursesCertificationProjects/Responsive-Web-Design/Tribute-Page
        destination_dir: tribute-page

    # Add more projects here as needed - just copy the pattern above
    # Example for a new project:
    # - name: Deploy My New Project
    #   if: hashFiles('CoursesCertificationProjects/Responsive-Web-Design/My-New-Project/index.html') != ''
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./CoursesCertificationProjects/Responsive-Web-Design/My-New-Project
    #     destination_dir: my-new-project

    - name: Create Portfolio Index
      run: |
        mkdir -p portfolio
        cat > portfolio/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>My freeCodeCamp Projects</title>
            <style>
                body { 
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                    max-width: 1000px; 
                    margin: 0 auto; 
                    padding: 40px 20px; 
                    background: #f5f5f5;
                }
                .container { 
                    background: white; 
                    padding: 40px; 
                    border-radius: 10px; 
                    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                }
                h1 { 
                    text-align: center; 
                    color: #2c3e50; 
                    margin-bottom: 40px;
                    font-size: 2.5em;
                }
                .projects { 
                    display: grid; 
                    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 30px; 
                    margin-top: 30px; 
                }
                .project-card { 
                    border: 1px solid #e1e8ed; 
                    padding: 30px; 
                    border-radius: 10px; 
                    transition: transform 0.2s, box-shadow 0.2s;
                    background: #fafafa;
                }
                .project-card:hover {
                    transform: translateY(-5px);
                    box-shadow: 0 8px 25px rgba(0,0,0,0.1);
                }
                .project-card h2 { 
                    margin-top: 0; 
                    color: #34495e;
                    font-size: 1.5em;
                }
                .project-link { 
                    display: inline-block; 
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white; 
                    padding: 12px 24px; 
                    text-decoration: none; 
                    border-radius: 6px; 
                    font-weight: 500;
                    transition: transform 0.2s;
                }
                .project-link:hover { 
                    transform: scale(1.05);
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 My freeCodeCamp Projects</h1>
                <div class="projects">
                    <div class="project-card">
                        <h2>📱 Product Landing Page</h2>
                        <p>A responsive product landing page showcasing modern web design principles.</p>
                        <a href="./product-landing-page/" class="project-link">View Project</a>
                    </div>
                    <div class="project-card">
                        <h2>📝 Survey Form</h2>
                        <p>An interactive survey form with validation and responsive design.</p>
                        <a href="./survey-form/" class="project-link">View Project</a>
                    </div>
                    <div class="project-card">
                        <h2>📚 Technical Documentation</h2>
                        <p>A comprehensive technical documentation page with navigation.</p>
                        <a href="./technical-documentation/" class="project-link">View Project</a>
                    </div>
                    <div class="project-card">
                        <h2>🏛️ Tribute Page</h2>
                        <p>A tribute page demonstrating clean layout and typography.</p>
                        <a href="./tribute-page/" class="project-link">View Project</a>
                    </div>
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Deploy Portfolio Index
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./portfolio
        keep_files: true
